apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-prod
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-prod
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki-stack
      targetRevision: 2.10.2
      helm:
        releaseName: loki-prod
        valueFiles:
          - $values/value_files/loki-values-prod.yaml
    - repoURL: https://github.com/sagiv-Ha/DevExpert_Monitoring.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true