apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-dev
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 82.14.1
      helm:
        releaseName: monitoring-dev
        skipCrds: true
        valueFiles:
          - $values/value_files/values-dev.yaml
    - repoURL: https://github.com/sagiv-Ha/DevExpert_Monitoring.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true